### ISSUE TITLE
lottery.js cannot do auto stop if setting.once is true

### ISSUE THREAD

**Issue by kiuchiy** [meetmore/lottery.js#3]
I tried your great software!
but lottery.js cannot do auto stop if setting.once is true.
I guess this bug happen "console.log('Lottery: dup, next.') execute once.

my config in index.html:

$.lottery({
  el: '.lotterybox',
  api: 'sample-data.json',
  once: true,
  subtitle: 'company',
  timeout: 3
});

thanks.

**Comment by Nekotora** [comment]
Sorry,I can't recurrent that.
Please make sure that you have enough user to get in lottery,
Maybe ramdom always get the user who has already won, and get into next round. It will be fix soon.
